---
title: "ML for Regression Models"
author: "Cam Smithers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rsample)
library(caret)
library(h2o)
library(modeldata)
library(vip)
library(ROCR)
library(dplyr)
```

# Model Testing

```{r}
#Setting seed to ensure reproducibility
set.seed(123)
```

```{r, include=FALSE, eval=FALSE}
nba_data <- all_team_data %>%
    select(-team_close_win, -team_cover_spread, -team_upset, -team_create_upset) %>%
    filter(if_all(everything(), ~ !is.na(.))) %>%
    mutate(team_winloss = as.factor(team_winloss))
```


```{r}
nba_data <- all_team_data %>%
    filter(!is.na(team_winloss)
           & !is.na(team_moneyline) 
           & !is.na(team_home) 
           & !is.na(avg_team_offrating) 
           & !is.na(avg_team_defrating) 
           & !is.na(avg_opponent_team_offrating) 
           & !is.na(avg_opponent_team_defrating) 
           & !is.na(team_upset_cumsum_rate))
#    select(team_winloss, team_moneyline, team_home, 
#           avg_team_offrating, avg_team_defrating, 
#           avg_opponent_team_offrating, avg_opponent_team_defrating,
#           team_upset_cumsum_rate) %>%
#    mutate(team_winloss = as.factor(team_winloss))
```

```{r}

#Splitting Data
nba_team_split <- initial_split(nba_data, prop = .60)
nba_team_train <- training(nba_team_split)
nba_team_test <- testing(nba_team_split)

#Win Loss Null Model
ml_null_winloss_model <- glm(team_winloss ~ team_moneyline
                          , data = nba_team_train
                        , family = binomial)

#Win Loss Model 1
ml_winloss_model <- glm(team_winloss ~ team_home 
                     + avg_team_offrating 
                     + avg_team_defrating
                     + avg_opponent_team_offrating
                     + avg_opponent_team_defrating
                     ,data = nba_team_train
                     , family = binomial)
#Win Loss Model 3
ml_winloss_model_v3 <- glm(team_winloss ~ team_home 
                     + avg_team_offrating 
                     + avg_team_defrating
                     + avg_opponent_team_offrating
                     + avg_opponent_team_defrating
                     + team_upset_cumsum_rate
                     ,data = nba_team_train
                     , family = binomial)

summary(ml_null_winloss_model)
summary(ml_winloss_model)
summary(ml_winloss_model_v3)
```

```{r}

#Win Loss Null Model
cv_ml_null_winloss_model <- train(team_winloss ~ team_moneyline
                          , data = nba_team_train
                          , method = "glm"
                        , family = binomial
                        , trControl = trainControl(method = "cv", number = 5))

#Win Loss Model 1
cv_ml_winloss_model <- train(team_winloss ~ team_home 
                     + avg_team_offrating 
                     + avg_team_defrating
                     + avg_opponent_team_offrating
                     + avg_opponent_team_defrating
                     , data = nba_team_train
                     , method = "glm"
                     , family = binomial
                     , trControl = trainControl(method = "cv", number = 5))
#Win Loss Model 3
cv_ml_winloss_model_v3 <- train(team_winloss ~ team_home 
                     + avg_team_offrating 
                     + avg_team_defrating
                     + avg_opponent_team_offrating
                     + avg_opponent_team_defrating
                     + team_upset_cumsum_rate
                     , data = nba_team_train
                     , method = "glm"
                     , family = binomial
                     , trControl = trainControl(method = "cv", number = 5))

summary(
    resamples(
        list(
        model1 = cv_ml_null_winloss_model,
        model2 = cv_ml_winloss_model,
        model3 = cv_ml_winloss_model_v3
        )
    )
)$statistics$Accuracy
```

```{r}
pred_class<- predict(cv_ml_winloss_model_v3, nba_team_train)

confusionMatrix(
    data = relevel(pred_class, ref = 1),
    reference = relevel(nba_team_train$team_winloss, ref = 1)
)
```

```{r}
m1_prob <- predict(cv_ml_null_winloss_model, nba_team_train, type = "prob")$"1"
m2_prob <- predict(cv_ml_winloss_model, nba_team_train, type = "prob")$"1"
m3_prob <- predict(cv_ml_winloss_model_v3, nba_team_train, type = "prob")$"1"


pref1 <- prediction(m1_prob, nba_team_train$team_winloss) %>%
    performance(measure = "tpr", x.measure = "fpr")

pref2 <- prediction(m2_prob, nba_team_train$team_winloss) %>%
    performance(measure = "tpr", x.measure = "fpr")

pref3 <- prediction(m3_prob, nba_team_train$team_winloss) %>%
    performance(measure = "tpr", x.measure = "fpr")

plot(pref1, col = "black", lty = 2, main = "ROC Curves")
plot(pref2, add = TRUE, col = "blue", lty = 1)
plot(pref3, add = TRUE, col = "red", lty = 3)
abline(0, 1, col = "gray", lty = 2) # Diagonal reference line

# Add legend
legend("bottomright", 
       legend = c("Model 1", "Model 2", "Model 3"),
       col = c("black", "blue", "red"), lty = c(2, 1, 3), cex = 0.8)
```
