---
title: "Model Analysis and ML"
author: "Cam Smithers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Model Analysis and Machine Learning

## Necessary Packages

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(foreign)
library(nnet)
```

## Data

```{r}
team_analysis_data <- readRDS("/Users/camsmithers/Desktop/NBA Project/Main/Data/cleaned_nba_data.rds")
```

# Model Analysis

## Mutations for Analysis

```{r}
ma_all_team_data <- all_team_data %>%
    mutate(my_predicted_win = ifelse(winloss_predicted_values > 50, 1, 0),
           my_model_correct = ifelse(my_predicted_win == team_game_outcome_2, 1, 0),
           diff_from_fanduel = ifelse(my_predicted_win != team_favored, 1, 0), 
           my_predicted_upset_1 = ifelse(upset_predicted_values > 50, 1, 0),
           my_predicted_upset_2 = ifelse(upset_predicted_values > winloss_predicted_values, 1, 0)) %>%
    mutate(fanduel_correct = ifelse(team_favored == team_game_outcome_2, 1, 0)) %>%
    filter(!is.na(team_fgm)) %>%
    filter(team_cumsum_game >= 10) %>%
    mutate(my_predicted_win_factor = factor(my_predicted_win,
                                            levels = c(0, 1),
                                            labels = c("exploss", "expwin")),
           team_game_outcome_2_factor = factor(team_game_outcome_2,
                                               levels = c(0, 1),
                                               labels = c("loss", "win")),
           team_favored_factor = factor(team_favored,
                                        levels = c(0, 1),
                                        labels = c("exploss", "expwin")),
           my_predicted_upset_1_factor = factor(my_predicted_upset_1,
                                                levels = c(0, 1),
                                                labels = c("no exp upset", "exp upset")),
           my_predicted_upset_2_factor = factor(my_predicted_upset_2,
                                                levels = c(0, 1),
                                                labels = c("no exp upset", "exp upset")),
           team_game_outcome_3_factor = factor(team_game_outcome_3, 
                                               levels = c(0, 1),
                                               labels = c("no upset", "upset")))
```

## Sensitivity, Specificity, and Accuracy

```{r}
cross_table_1 <- table(ma_all_team_data$my_predicted_upset_1_factor, ma_all_team_data$team_game_outcome_3_factor)
print(cross_table_1)
addmargins(cross_table_1)
prop.table(cross_table_1)

cross_table_2 <- table(ma_all_team_data$my_predicted_upset_2_factor, ma_all_team_data$team_game_outcome_3_factor)
print(cross_table_2)
addmargins(cross_table_2)
prop.table(cross_table_2)
```

------------------------------------------------------------------------

# Machine Learning: Model Testing

## *Current Model: Margin of Victory*

## Necessary Packages

```{r eval=FALSE, include=FALSE}
library(rsample)
library(caret)
library(h2o)
library(modeldata)
library(vip)
library(ROCR)
```

## Needed Variables

```{r eval=FALSE, include=FALSE}
set.seed(1234)
ml_all_team_data <- all_team_data %>%
    dplyr::select(team_date, team_team, team_game_outcome, team_home, 
           team_moneyline)
ml_all_team_data <- na.omit(ml_all_team_data)
```

## Factoring Before Analysis

```{r eval=FALSE, include=FALSE}
ml_all_team_data <- ml_all_team_data %>%
    mutate(team_game_outcome = factor(team_game_outcome,
                                        levels = c(1, 2, 3, 4),
                                        labels = c("close_win", "close_loss",
                                                   "blowout_win", "blowout_loss")))
```

## Splitting Data & Creating Models

```{r eval=FALSE, include=FALSE}
#Splitting Data
ml_team_split <- initial_split(ml_all_team_data, prop = .60)
ml_team_train <- training(ml_team_split)
ml_team_test <- testing(ml_team_split)

#Models
ml_team_outcome_fd <- multinom(team_game_outcome ~ team_moneyline,
                               data = ml_team_train)

ml_team_outcome <- multinom(team_game_outcome ~ team_home 
                            + team_cummean_pts_win
                            + team_cummean_pts_allowed_win
                            + opponent_cummean_pts_loss
                            + opponent_cummean_pts_allowed_loss
                            + team_cummean_pts_loss
                            + team_cummean_pts_allowed_loss
                            + opponent_cummean_pts_win
                            + opponent_cummean_pts_allowed_win
                           , data = ml_team_train)

summary(ml_team_outcome_fd)
summary(ml_team_outcome)
```

## Cross Validation

```{r eval=FALSE, include=FALSE}
cv_ml_team_outcome_fd <- train(team_game_outcome ~ team_moneyline
                            , data = ml_team_train
                            , method = "multinom"
                            , trControl = trainControl(method = "cv", number = 5))

cv_ml_team_outcome <- train(team_game_outcome ~ team_home 
                            + team_cummean_pts_win
                            + team_cummean_pts_allowed_win
                            + opponent_cummean_pts_loss
                            + opponent_cummean_pts_allowed_loss
                            , data = ml_team_train
                           , method = "multinom"
                           , trControl = trainControl(method = "cv", number = 5))



summary(
    resamples(
        list(
            model1 = cv_ml_team_outcome_fd,
            model2 = cv_ml_team_outcome
        )
    )
)$statistics$Accuracy
```

```{r eval=FALSE, include=FALSE}
pred_class <- predict(cv_ml_team_outcome, ml_team_train)
confusionMatrix(
    data = pred_class,
    reference = relevel(ml_team_train$team_game_outcome, ref = 1)
)
```
