---
title: "Model Visualizations"
author: "Cam Smithers"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Model Visualizations

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(patchwork)
library(readxl)
#library(plotly)
```

# Data and Extra Global Vars

```{r}
team_visual_data <- readRDS("/Users/camsmithers/Desktop/NBA Project/Main/Data/cleaned_nba_data.rds")

camalytics_predictions <- read_excel("/Users/camsmithers/Desktop/NBA Project/Main/Data/CamalyticsPicks.xlsx")

current_date <- format(Sys.Date(), "%m_%d_%y")
```

# Post Modeling Cleaning

```{r}
team_visual_data <- team_visual_data %>%
    mutate(outcome_2_estimates_categories = case_when(
        # Category 1
        
        winloss_predicted_values >= 50 & winloss_predicted_values < 65 
        & upset_predicted_values >= 50 ~ 1,
        
        # Category 2
        winloss_predicted_values >= 65 & upset_predicted_values >= 50 ~ 2,
        
        # Category 3
        winloss_predicted_values >= 50 & winloss_predicted_values < 65 & 
            upset_predicted_values >= 25 & upset_predicted_values < 50 ~ 3,
        
        # Category 4
        (winloss_predicted_values >= 50 & winloss_predicted_values < 65 & upset_predicted_values < 25) | 
        (winloss_predicted_values >= 65 & upset_predicted_values >= 25 & upset_predicted_values < 50) ~ 4,
        
        # Category 5
        winloss_predicted_values >= 65 & upset_predicted_values < 25 ~ 5,
        
        # Category 0
        winloss_predicted_values < 50 ~ 0
    )) %>%
    mutate(outcome_2_estimates_factor = factor(outcome_2_estimates_categories,
                                               levels = c(0, 1, 2, 3, 4, 5),
                                               labels = c("Not Favored", "Very Unlikely", "Unlikely", "Coin Flip", "Likely", "Very Likely"))) %>%
    mutate(team_name = case_when(
        #Atlantic Division
        team_team == "bos" ~ "Boston Celtics",
        team_team == "bkn" ~ "Brooklyn Nets",
        team_team == "nyk" ~ "New York Knicks",
        team_team == "phi" ~ "Philadelphia 76ers",
        team_team == "tor" ~ "Toronto Raptors",
        #Central Division
        team_team == "chi" ~ "Chicago Bulls",
        team_team == "cle" ~ "Cleveland Cavaliers",
        team_team == "det" ~ "Detroit Pistons",
        team_team == "ind" ~ "Indiana Pacers",
        team_team == "mil" ~ "Milwaukee Bucks",
        #Southeast Division
        team_team == "atl" ~ "Atlanta Hawks",
        team_team == "cha" ~ "Charlotte Hornets",
        team_team == "mia" ~ "Miami Heat",
        team_team == "orl" ~ "Orlando Magic",
        team_team == "was" ~ "Washington Wizards",
        #Northwest Division
        team_team == "den" ~ "Denver Nuggets",
        team_team == "min" ~ "Minnesota Timberwolves",
        team_team == "okc" ~ "Oklahoma City Thunder",
        team_team == "por" ~ "Portland Trail Blazers",
        team_team == "uta" ~ "Utah Jazz",
        #Pacific Division
        team_team == "gsw" ~ "Golden State Warriors",
        team_team == "lac" ~ "Los Angeles Clippers",
        team_team == "lal" ~ "Los Angeles Lakers",
        team_team == "phx" ~ "Phoenix Suns",
        team_team == "sac" ~ "Sacramento Kings",
        #Southwest Division
        team_team == "dal" ~ "Dallas Mavericks",
        team_team == "hou" ~ "Houston Rockets",
        team_team == "mem" ~ "Memphis Grizzlies",
        team_team == "nop" ~ "New Orleans Pelicans",
        team_team == "sas" ~ "San Antonio Spurs")) %>%
    mutate(opponent_name = case_when(
        #Atlantic Division
        team_opponent == "bos" ~ "Boston Celtics",
        team_opponent == "bkn" ~ "Brooklyn Nets",
        team_opponent == "nyk" ~ "New York Knicks",
        team_opponent == "phi" ~ "Philadelphia 76ers",
        team_opponent == "tor" ~ "Toronto Raptors",
        #Central Division
        team_opponent == "chi" ~ "Chicago Bulls",
        team_opponent == "cle" ~ "Cleveland Cavaliers",
        team_opponent == "det" ~ "Detroit Pistons",
        team_opponent == "ind" ~ "Indiana Pacers",
        team_opponent == "mil" ~ "Milwaukee Bucks",
        #Southeast Division
        team_opponent == "atl" ~ "Atlanta Hawks",
        team_opponent == "cha" ~ "Charlotte Hornets",
        team_opponent == "mia" ~ "Miami Heat",
        team_opponent == "orl" ~ "Orlando Magic",
        team_opponent == "was" ~ "Washington Wizards",
        #Northwest Division
        team_opponent == "den" ~ "Denver Nuggets",
        team_opponent == "min" ~ "Minnesota Timberwolves",
        team_opponent == "okc" ~ "Oklahoma City Thunder",
        team_opponent == "por" ~ "Portland Trail Blazers",
        team_opponent == "uta" ~ "Utah Jazz",
        #Pacific Division
        team_opponent == "gsw" ~ "Golden State Warriors",
        team_opponent == "lac" ~ "Los Angeles Clippers",
        team_opponent == "lal" ~ "Los Angeles Lakers",
        team_opponent == "phx" ~ "Phoenix Suns",
        team_opponent == "sac" ~ "Sacramento Kings",
        #Southwest Division
        team_opponent == "dal" ~ "Dallas Mavericks",
        team_opponent == "hou" ~ "Houston Rockets",
        team_opponent == "mem" ~ "Memphis Grizzlies",
        team_opponent == "nop" ~ "New Orleans Pelicans",
        team_opponent == "sas" ~ "San Antonio Spurs"))

dummy_data <- team_visual_data %>%
    select(team_date, team_team, upset_predicted_values) %>%
    rename("dummy_team"="team_team", "opponent_upset_predicted_values"="upset_predicted_values")

team_visual_data <- team_visual_data %>%
    left_join(dummy_data, by = c("team_opponent"="dummy_team", "team_date")) %>%
    mutate(
        nba_picks = case_when(
            upset_predicted_values < (25 / 65) * winloss_predicted_values ~ 2,
            upset_predicted_values < (37.5 / 75) * winloss_predicted_values ~ 1,
        TRUE ~ 0),
        nba_picks_factor = factor(nba_picks,
                                     levels = c(0, 1, 2),
                                     labels = c("Avoid", "Consider", "Select")),
        team_display = toupper(team_team),
        plusminus_inrange = case_when(
            (outcome_margin_predicted_values %in% 0:10 & team_plusminus %in% 1:10) 
            | (outcome_margin_predicted_values %in% -1:-10 & team_plusminus %in% -1:-10)
            | (outcome_margin_predicted_values > 10 & team_plusminus > 10)
            | (outcome_margin_predicted_values < -10 & team_plusminus < -10) ~ 1,
            (outcome_margin_predicted_values >= 0 & team_plusminus > 0)
            | (outcome_margin_predicted_values < 0 & team_plusminus < 0) ~ 0,
            TRUE ~ NA),
        plusminus_inrange_factor = factor(plusminus_inrange,
                                          levels = c(0, 1),
                                          labels = c("Close", "Money")))
```

# Daily Visualizations

## Data Cleaning

```{r}
daily.team_visual_data <- team_visual_data %>%
    mutate(my_predicted_win = ifelse(winloss_predicted_values > 50, 1, 0),
           my_model_correct = ifelse(my_predicted_win == team_game_outcome_2, 1, 0),
           diff_from_fanduel = ifelse(my_predicted_win != team_favored, 1, 0), 
           my_predicted_upset = ifelse(upset_predicted_values > 50, 1, 0)) %>%
    mutate(fanduel_correct = ifelse(team_favored == team_game_outcome_2, 1, 0)) %>%
    filter(team_cumsum_game >= 5) %>%
    filter(!is.na(upset_predicted_values)) %>%
    filter(team_date == Sys.Date())
```

## Visualizations

```{r}

daily.outcome_plot_1 <- ggplot(daily.team_visual_data,
                               aes(x = winloss_predicted_values,
                                   y = upset_predicted_values,
                                   color = team_name)) + 
    geom_vline(xintercept = 65, color = "black", linetype = "dashed") +
    geom_hline(yintercept = 50, color = "black", linetype = "dashed") + 
    geom_hline(yintercept = 25, color = "black", linetype = "dashed") + 
    geom_abline(slope = 25/65, color = "springgreen3", linetype = "solid") +
    geom_abline(slope = 37.5/75, color = "gold2", linetype = "solid") +
    geom_point(size = 5) + 
    geom_text(aes(label = team_display), 
              hjust = -0.3, vjust = 1.5, size = 3.5) + 
    scale_x_continuous(limits = c(50, 100)) + 
    theme_bw() +
    labs(
    title = "Win & Upset Probability", 
    x = "Win Probability", 
    y = "Upset Probability", 
    color = "Teams")
daily.outcome_plot_1
#ggsave(filename = paste0("game_splitting_", current_date, ".png"), 
#       plot = daily.outcome_plot_1,
#       path = "/Users/camsmithers/Desktop/NBA Project/Main/Visualizations", 
#       width = 35, height = 20, units = "cm")
```

# Daily Historic Visualizations

## Data Cleaning

```{r}
all.team_visual_data <- team_visual_data %>%
    mutate(
        my_predicted_win = ifelse(winloss_predicted_values > 50, 1, 0),
        my_model_correct = ifelse(my_predicted_win == team_game_outcome_2, 1, 0),
        diff_from_fanduel = ifelse(my_predicted_win != team_favored, 1, 0), 
        my_predicted_upset = ifelse(upset_predicted_values > 50, 1, 0), 
        fanduel_correct = ifelse(team_favored == team_game_outcome_2, 1, 0)) %>%
    filter(
        !is.na(team_fgm),
        team_cumsum_game >= 5,
        !is.na(upset_predicted_values),
        team_date != Sys.Date(),
        team_team %in% daily.team_visual_data$team_team)
```

## Visualizations

```{r}
all.outcome_plot_1 <- ggplot(all.team_visual_data,
                             aes(x = nba_picks_factor,
                                 fill = as.factor(team_game_outcome_2))) + 
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    facet_wrap(~team_name) +
    labs(
        title = "Win History in Pick Class",
        x = "Pick Class",
        y = "Count",
        fill = "Outcome") + 
    theme_bw() + 
    scale_fill_manual(values = c("0"="red3", "1"="cornflowerblue"),
                       labels = c("0"="Loss", "1"="Win")) + 
    scale_y_continuous(limits = c(0, 25), breaks = c(5, 10, 15, 20, 25))
all.outcome_plot_1
#ggsave(filename = paste0("game_picks_ratio_", current_date, ".png"), 
#       plot = all.outcome_plot_1,
#       path = "/Users/camsmithers/Desktop/NBA Project/Main/Visualizations", 
#       width = 35, height = 20, units = "cm")

all.outcome_plot_2 <- ggplot(all.team_visual_data,
                             aes(x = outcome_2_estimates_factor,
                                 fill = as.factor(team_game_outcome_2))) + 
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    facet_wrap(~team_name) +
    labs(
        title = "Win History in Relation to Zones",
        x = "Game Category",
        y = "Count",
        fill = "Outcome") + 
    theme_bw() + 
    scale_fill_manual(values = c("0"="red3", "1"="cornflowerblue"),
                       labels = c("0"="Loss", "1"="Win")) + 
    scale_y_continuous(limits = c(0, 25), breaks = c(5, 10, 15, 20, 25))
all.outcome_plot_2
#ggsave(filename = paste0("game_splitting_ratio_", current_date, ".png"), 
#       plot = all.outcome_plot_2,
#       path = "/Users/camsmithers/Desktop/NBA Project/Main/Visualizations", 
#       width = 35, height = 20, units = "cm")
```

# Historic Visualizations

## Data Cleaning

```{r}
historic.team_visual_data <- team_visual_data %>%
    mutate(
        my_predicted_win = ifelse(winloss_predicted_values > 50, 1, 0),
        my_model_correct = ifelse(my_predicted_win == team_game_outcome_2, 1, 0),
        diff_from_fanduel = ifelse(my_predicted_win != team_favored, 1, 0), 
        my_predicted_upset = ifelse(upset_predicted_values > 50, 1, 0), 
        fanduel_correct = ifelse(team_favored == team_game_outcome_2, 1, 0)) %>%
    mutate(my_adjusted_model = case_when(
        winloss_predicted_values > 50 & upset_predicted_values < 50 ~ 1,
        winloss_predicted_values > 50 & upset_predicted_values >= 50 ~ 0, 
        winloss_predicted_values < 50 & opponent_upset_predicted_values >= 50 ~ 1,
        winloss_predicted_values < 50 & opponent_upset_predicted_values < 50 ~ 0)) %>%
    mutate(my_adjusted_model_correct = ifelse(my_adjusted_model == team_game_outcome_2, 1, 0)) %>%
    mutate() %>%
    filter(
        !is.na(team_fgm),
        team_cumsum_game >= 5,
        !is.na(upset_predicted_values),
        team_date != Sys.Date())
```

## Visualizations

```{r}
historic.outcome_plot_1 <-  ggplot(historic.team_visual_data, 
                              aes(x = winloss_predicted_values,
                                  y = upset_predicted_values,
                                  color = as.factor(team_game_outcome_2))) + 
    geom_vline(xintercept = 65, color = "black", linetype = "dashed") +
    geom_hline(yintercept = 50, color = "black", linetype = "dashed") + 
    geom_hline(yintercept = 25, color = "black", linetype = "dashed") + 
    geom_hline(yintercept = 37.5, color = "black", linetype = "dashed") + 
    geom_abline(slope = 37.5/75, color = "gold2", linetype = "solid") + 
    geom_abline(slope = 25/65, color = "springgreen3", linetype = "solid") + 
    geom_point() +
    scale_x_continuous(limits = c(50, 100)) + 
    theme_bw() +
#    facet_wrap(~team_name) +
    labs(
        title = "Win & Upset Probability History",
        x = "Win Probability",
        y = "Upset Probability", 
        color = "Outcome") + 
    scale_color_manual(values = c("0"="red3", "1"="cornflowerblue"),
                       labels = c("0"="Loss", "1"="Win")) +
    facet_wrap(~team_display)
#historic.outcome_plot_1
#ggsave(filename = paste0("game_splitting_history_2", current_date, ".png"), 
#       plot = historic.outcome_plot_1,
#       path = "/Users/camsmithers/Desktop/NBA Project/Main/Visualizations", 
#       width = 100, height = 100, units = "cm")

historic.outcome_plot_2 <- ggplot(historic.team_visual_data,
                             aes(x = outcome_2_estimates_factor,
                                 fill = as.factor(team_game_outcome_2))) + 
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    facet_wrap(~nba_picks_factor) +
    labs(
        title = "Win History in Relation to Zones",
        x = "Game Category",
        y = "Count",
        fill = "Outcome") + 
    theme_bw() + 
    scale_fill_manual(values = c("0"="red3", "1"="cornflowerblue"),
                       labels = c("0"="Loss", "1"="Win"))
historic.outcome_plot_2
#ggsave(filename = paste0("game_splitting_ratio_", current_date, ".png"), 
#       plot = all.outcome_plot_2,
#       path = "/Users/camsmithers/Desktop/NBA Project/Main/Visualizations", 
#       width = 35, height = 25, units = "cm")

historic.outcome_plot_a <- ggplot(historic.team_visual_data, 
                                  aes(x = my_adjusted_model_correct, 
                                      fill = as.factor(my_adjusted_model_correct))) +
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    labs(
        title = "Win Model Adjusted for Upset Probability",
        x = "Incorrect vs. Correct Picks",
        y = "Count",
        fill = "Picks") + 
    facet_wrap(~nba_picks_factor) +
    theme_bw() + 
    scale_fill_manual(values = c("0"="red3", "1"="springgreen3"),
                       labels = c("0"="Incorrect", "1"="Correct"))
#historic.outcome_plot_a


historic.outcome_plot_b <- ggplot(historic.team_visual_data, 
                                  aes(x = my_model_correct, 
                                      fill = as.factor(my_model_correct))) +
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    labs(
        title = "Raw Unadjusted Win Model",
        x = "Incorrect vs. Correct Picks",
        y = "Count",
        fill = "Picks") + 
#    facet_wrap(~team_name) +
    theme_bw() +
    scale_fill_manual(values = c("0"="red3", "1"="springgreen3"),
                       labels = c("0"="Incorrect", "1"="Correct"))
#historic.outcome_plot_b

historic.outcome_plot_c <- ggplot(historic.team_visual_data, 
                                  aes(x = fanduel_correct, 
                                      fill = as.factor(fanduel_correct))) +
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    labs(
        title = "Fanduel Model",
        x = "Incorrect vs. Correct Picks",
        y = "Count",
        fill = "Picks") + 
    facet_wrap(~nba_picks_factor) +
    theme_bw() +
    scale_fill_manual(values = c("0"="red3", "1"="springgreen3"),
                       labels = c("0"="Incorrect", "1"="Correct"))
#historic.outcome_plot_c

historic.outcome_plot_d <- ggplot(historic.team_visual_data,
                             aes(x = winloss_predicted_values, 
                                 y = team_plusminus)) + 
    geom_hline(yintercept = 0, color = "red", linetype = "solid") +
    geom_vline(xintercept = 80, color = "green", linetype = "solid") +
    geom_point() + 
    geom_smooth() + 
    facet_wrap(~nba_picks_factor)
historic.outcome_plot_d

#cam_vs_fanduel <- historic.outcome_plot_a + historic.outcome_plot_c + 
#    plot_layout(ncol = 2) + 
#    plot_annotation(title = "Cam vs. Fanduel Models",
#                    theme = theme(plot.title = element_text(hjust = 0.5)))
#cam_vs_fanduel

historic.outcome_plot_e <- ggplot(historic.team_visual_data %>% filter(!is.na(plusminus_inrange_factor)),
                                  aes(x = plusminus_inrange_factor,
                                      fill = as.factor(plusminus_inrange_factor))) +
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) +
    facet_wrap(team_name~nba_picks_factor) +
    theme_bw() +
    labs(
        title = "Team Point Range in Relation to Pick Breakdown",
        x = "Point Estimate in Relation to Outcome",
        y = "Count",
        fill = "Point Range Outcome")
historic.outcome_plot_e
```

# Camalytics Picks

## Data Cleaning

```{r}
camalytics_predictions_data <- camalytics_predictions %>%
    left_join(team_visual_data, by = c("camalytics_picks"="team_team", "date"="team_date")) %>%
    mutate(picks_zone = ifelse(outcome_2_estimates_categories %in% 1:5,
                               "Picked Favorite", "Picked Upset")) %>%
    mutate(
        my_predicted_win = ifelse(winloss_predicted_values > 50, 1, 0),
        my_model_correct = ifelse(my_predicted_win == team_game_outcome_2, 1, 0),
        diff_from_fanduel = ifelse(my_predicted_win != team_favored, 1, 0), 
        my_predicted_upset = ifelse(upset_predicted_values > 50, 1, 0), 
        fanduel_correct = ifelse(team_favored == team_game_outcome_2, 1, 0)) %>%
    mutate(my_adjusted_model = case_when(
        winloss_predicted_values > 50 & upset_predicted_values < 50 ~ 1,
        winloss_predicted_values > 50 & upset_predicted_values >= 50 ~ 0, 
        winloss_predicted_values < 50 & opponent_upset_predicted_values >= 50 ~ 1,
        winloss_predicted_values < 50 & opponent_upset_predicted_values < 50 ~ 0)) %>%
    mutate(my_adjusted_model_correct = ifelse(my_adjusted_model == team_game_outcome_2, 1, 0))
```

## Visualizations

```{r}
camalytics_plot_1 <- ggplot(camalytics_predictions_data,
                            aes(x = my_adjusted_model_correct,
                                fill = as.factor(my_adjusted_model_correct))) + 
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    labs(
        title = "Camalytics Predictions",
        x = "Game Result",
        y = "Count",
        fill = "Pick Result") + 
    theme_bw() + 
    scale_fill_manual(values = c("0"="red3", "1"="springgreen3"),
                       labels = c("0"="Incorrect", "1"="Correct"))
#    facet_wrap(~picks_zone)
camalytics_plot_1

fanduel_plot_1 <- ggplot(camalytics_predictions_data,
                            aes(x = fanduel_correct,
                                fill = as.factor(fanduel_correct))) + 
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count", 
              aes(label = after_stat(count)), 
              position = position_dodge(width = 0.9), 
              vjust = -0.5) + 
    labs(
        title = "Fanduel Predictions",
        x = "Game Result",
        y = "Count",
        fill = "Pick Result") + 
    theme_bw() + 
    scale_fill_manual(values = c("0"="red3", "1"="springgreen3"),
                       labels = c("0"="Incorrect", "1"="Correct"))
#    facet_wrap(~picks_zone)
fanduel_plot_1
```
